version: '3'
services:
  airflow:
    build: .
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./models:/opt/airflow/models
      - ./logs:/opt/airflow/logs
    command: webserver
    ports:
      - 8080:8080
